name: dado
version: 0.5.0
author: Dart Authors <misc@dartlang.org>
description: An experimental dependency injection container for Dart
homepage: https://github.com/dart-lang/dado
dependencies:
  logging: any
dev_dependencies:
  unittest: any
