name: symbiosis
version: 0.6.0
authors:
- Diego Rocha <diego.rocha.comp@gmail.com>
- Dart Authors <misc@dartlang.org>
description: A dependency injection framework for Dart
dependencies:
  inject: '>=0.0.1'
  logging: '>=0.9.1'
  quiver: '>=0.17.0'
dev_dependencies:
  unittest: '>=0.9.2'
