name: symbiosis
version: 0.6.0
authors:
- Diego Rocha <diego.rocha.comp@gmail.com>
- Dart Authors <misc@dartlang.org>
description: A dependency injection framework for Dart
homepage: https://github.com/Dreckr/Symbiosis
environment:
  sdk: '>=1.3.0'
dependencies:
  collection: '>=0.9.2 <0.10.0'
  inject: '>=0.1.0 <0.2.0'
  quiver: '>=0.18.0 <0.19.0'
dev_dependencies:
  benchmark_harness: any
  unittest: '>=0.9.2 <0.10.0'
