name: dado
description: An experimental dependency injection container for Dart 
version: 0.4.2
author: "Dart Authors <misc@dartlang.org>"
homepage: https://github.com/dart-lang/dado

dependencies:
  logging: any

dev_dependencies:
  unittest: any
